# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 04:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confile', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='conversion/%Y%m%d'), upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.ImageField(upload_to='documents/%Y%m%d')),
            ],
        ),
    ]
